### ISSUE TITLE
/.kube/config: no such file or directory

### ISSUE THREAD

**Issue by psarossy** [arminc/k8s-platform-lcm#121]
Trying to run LCM out of the box with the docker image doesn't work, and there are no instructions what I should be doing instead...

```
$ docker run -it -v $(pwd)/config.yaml:/config.yaml -p 7321:7321 arminc/lcm:latest --local                                                           [11:15:04]
ERRO[0000] Could not create a kubernetes client          error="Could not find kubernetes config: stat /.kube/config: no such file or directory"
+-------+---------+--------+------------+------+
| IMAGE | VERSION | LATEST | TOTAL CVES | CVES |
+-------+---------+--------+------------+------+
+-------+---------+--------+------------+------+
ERRO[0000] Failed to create helm client                  error="Could not create Kube client for helm usage: Could not find kubernetes config: stat /.kube/config: no such file or directory"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17ece0a]

goroutine 1 [running]:
github.com/arminc/k8s-platform-lcm/internal.getLatestVersionsForHelmCharts(0x1e1fcc0, 0xc000180008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /home/runner/work/k8s-platform-lcm/k8s-platform-lcm/internal/lcm.go:176 +0x10a
github.com/arminc/k8s-platform-lcm/internal.Execute(0x1, 0x1bc4c63, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/k8s-platform-lcm/k8s-platform-lcm/internal/lcm.go:72 +0x637
main.main()
        /home/runner/work/k8s-platform-lcm/k8s-platform-lcm/cmd/lcm/main.go:62 +0x1f8
FAIL: 2
```

**Comment by arminc** [comment]
If you are using the container locally you will need to add one more volume, your ".kube/config" so that the tool can talk to Kubernetes.

**Comment by psarossy** [comment]
@arminc well, the instructions in the README don't talk about that, nor any other method of running this image, so that's not super user friendly...

Adding the volume for the path in the previous error message yields a new error message:

```
$ docker run -it -v $(pwd)/config.yaml:/config.yaml -v ~/.kube/config:/.kube/config -p 7321:7321 arminc/lcm:latest --local                                                                                                                                                                                                                                                     [17:22:38]
panic: interface conversion: reference.canonicalReference is not reference.NamedTagged: missing method Tag

goroutine 1 [running]:
github.com/arminc/k8s-platform-lcm/pkg/kubernetes.ImagePathToImage(0xc000935110, 0x6d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/k8s-platform-lcm/k8s-platform-lcm/pkg/kubernetes/images.go:32 +0xc9
github.com/arminc/k8s-platform-lcm/pkg/kubernetes.k8sClient.GetImagesFromNamespaces(0xc000268000, 0x1e1fcc0, 0xc000040018, 0xc00018f400, 0x22, 0x0, 0x179cc1b, 0x1a3f5c0, 0xc000182750, 0x0, ...)
        /home/runner/work/k8s-platform-lcm/k8s-platform-lcm/pkg/kubernetes/k8s.go:65 +0x389
github.com/arminc/k8s-platform-lcm/internal.Execute(0x1, 0x1bc4c63, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/k8s-platform-lcm/k8s-platform-lcm/internal/lcm.go:52 +0x9c8
main.main()
        /home/runner/work/k8s-platform-lcm/k8s-platform-lcm/cmd/lcm/main.go:62 +0x1f8
FAIL: 2
```
